### ISSUE TITLE
Handle spaces in Elixir Executable and Mix Executable settings 

### ISSUE THREAD

**Issue by rgreenjr** [rgreenjr/atom-elixir-formatter#9]
Users must double quote Elixir Executable and Mix Executable paths containing spaces.

**Comment by rgreenjr** [comment]
Fixed in 24a12ee0dffba6acbe6141356c581d107678697a

**Comment by indyone** [comment]
@rgreenjr we need to re-open this issue, as it is not fixed. 
You should add the path in double quotes, not the single ones, for making it work on Windows.
I think that double quotes also works on Linux.

**Comment by rgreenjr** [comment]
@indyone Thanks for testing on Windows. I just released v0.2.5, which uses double-quotes instead of single-quotes. That should work on Windows, macOS, and Linux. Please give it a try and let me know if you have any problems. Thanks.

**Comment by indyone** [comment]
@rgreenjr I confirm that as of v0.2.6 on Windows you don't need to add quote in the path when these contain spaces.
